# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/cs/
    binary: cs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: ./cmd/exo/
    binary: exo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

sign:
  cmd: gpg
  args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
  artifacts: none

archive:
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: exoscale
    name: egoscale
  draft: true

nfpm:

  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"


  vendor: Exoscale.
  

  homepage: https://www.exoscale.com/

  
  description: Tools to manage (almost) everything at Exoscale from the command line.

  license: Apache 2.0

  

  # Formats to be generated.
  formats:
    - deb
    - rpm

