language: go

dist: trusty
sudo: required

go:
- 1.9
- "1.10"
- tip

env:
  - DEP_VERSION=0.4.1 HUGO_VERSION=0.41 GORELEASER_VERSION=0.77.1

cache: apt

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  - sudo dpkg- i goreleaser_amd64.deb
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

jobs:
  include:
  - stage: test
    script: |
      dep ensure -v -vendor-only
      go test -race -coverprofile=coverage.out -covermode=atomic .
      npm i codeclimate-test-reporter
      npx codeclimate-test-reporter < coverage.out
  - stage: goreleaser
    script: |
      dep ensure -v -vendor-only
      cd cmd/cs
      dep ensure -v -vendor-only
      cd ../exo
      dep ensure -v -vendor-only
      cd ../..
      goreleaser --snapshot --skip-sign
  - stage: gh-pages
    script: |
      dep ensure -v -vendor-only
      cd cmd/exo
      dep ensure -v -vendor-only
      go run doc/main.go
      cd ../..
      cd website
      hugo
