// Code generated by "stringer -type=record"; DO NOT EDIT.

package cmd

import "strconv"

const _record_name = "AAAAAALIASCNAMEHINFOMXNAPTRNSPOOLSPFSRVSSHFPTXTURL"

var _record_index = [...]uint8{0, 1, 5, 10, 15, 20, 22, 27, 29, 33, 36, 39, 44, 47, 50}

func (i record) String() string {
	if i < 0 || i >= record(len(_record_index)-1) {
		return "record(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _record_name[_record_index[i]:_record_index[i+1]]
}
